query GetKit($id: Int!, $priceId: ID!, $currencyName: String) {
  kit(id: $id) {
    id
    type
    priceData(priceId: $priceId, currencyName: $currencyName) {
      mainProductPrice
      selectedProductPrice
      oldTotal
      newTotal
    }
    products {
      edges {
        node {
          id
          name
        }
      }
    }
  }
}
