mutation UpdateCartItem($cartItemIds: [ID], $count: Int, $isActive: Boolean) {
  changeCartItems(cartItems: $cartItemIds, count: $count, isActive: $isActive) {
    errors {
      messages
      field
    }
  }
}