fragment CategoryFields on ProductGroupNode {
  id
  slug
  name
  image(size: "300x300")
  breadCrumbs {
    id
    slug
    name
  }
  isActive
}

query GetCatalog {
  productGroupAll(level: 0) {
    edges {
      ...CategoryFields
    }
  }
}